In [1]:
import numpy as np


In [2]:
file = 'advent2024_2.txt'
with open(file, 'r') as f:
    real_data = f.read().splitlines()

In [3]:
real_data

['18 21 22 24 26 29 28',
 '9 11 14 17 18 21 21',
 '48 51 54 56 60',
 '6 8 10 11 16',
 '75 76 79 82 80 83',
 '28 31 33 32 33 30',
 '94 96 94 96 96',
 '42 44 45 44 46 50',
 '25 28 29 26 33',
 '37 39 39 42 43',
 '49 51 53 56 56 57 55',
 '88 91 91 93 96 99 99',
 '56 59 59 61 62 65 68 72',
 '30 33 35 37 39 42 42 49',
 '14 17 19 23 24',
 '2 4 5 9 12 15 16 14',
 '88 89 93 96 99 99',
 '68 70 71 74 78 81 85',
 '46 47 49 53 58',
 '36 39 41 47 49 50 51 54',
 '81 82 85 91 93 95 96 94',
 '11 14 16 18 23 23',
 '72 75 81 84 85 89',
 '40 41 44 46 51 53 58',
 '70 68 71 73 76 77 78 80',
 '83 80 83 86 83',
 '44 42 45 47 49 51 51',
 '78 77 80 81 83 85 88 92',
 '34 33 34 36 38 45',
 '54 51 52 54 56 57 56 59',
 '57 54 53 55 52',
 '48 46 47 49 47 47',
 '70 67 64 65 67 70 72 76',
 '42 41 42 45 44 46 53',
 '44 41 44 47 47 50 51 53',
 '12 11 13 13 12',
 '27 25 25 26 26',
 '57 55 55 58 61 65',
 '65 63 65 68 69 69 71 78',
 '88 87 91 93 94',
 '84 82 84 86 90 92 93 92',
 '22 21 25 27 28 28',
 '35 33 35 36 40 43 44 

In [32]:
count = 0
for element in real_data:
    sequence = np.array(element.split(' '), dtype=int)
    sequence_copy = sequence[1:-1]
    sequence_copy = np.append(sequence_copy, sequence[-1])
    sequence_copy = np.append(sequence_copy, sequence[0])
    diff = sequence - sequence_copy
    diff = np.abs(diff[0:-1])
    if (np.max(diff) < 4) and (np.min(diff) > 0):
        #print(sequence)
        # print(sequence_copy)
        # print(diff)
        ascending = np.sort(sequence)
        descending = np.sort(sequence)[::-1]
        if np.all(ascending == sequence) or np.all(descending == sequence):
            count += 1
            print(ascending, descending, sequence, "\n")
        # if np.sort(sequence) == sequence or np.sort(sequence)[::-1] == sequence:
        #     count += 1
    # print(sequence_copy, sequence, diff)
print(count)

[48 49 52 54 56 59 61 64] [64 61 59 56 54 52 49 48] [64 61 59 56 54 52 49 48] 

[44 45 46 47 49 50 53 55] [55 53 50 49 47 46 45 44] [55 53 50 49 47 46 45 44] 

[42 45 46 48 51 53 55] [55 53 51 48 46 45 42] [55 53 51 48 46 45 42] 

[65 67 70 72 74 75] [75 74 72 70 67 65] [65 67 70 72 74 75] 

[88 91 92 93 95 97 98] [98 97 95 93 92 91 88] [88 91 92 93 95 97 98] 

[91 92 93 95 96 99] [99 96 95 93 92 91] [99 96 95 93 92 91] 

[ 1  3  6  9 11] [11  9  6  3  1] [ 1  3  6  9 11] 

[64 66 68 70 72 73] [73 72 70 68 66 64] [73 72 70 68 66 64] 

[40 42 45 46 49] [49 46 45 42 40] [40 42 45 46 49] 

[56 57 59 60 62 65 67] [67 65 62 60 59 57 56] [56 57 59 60 62 65 67] 

[49 51 54 57 59 60 62 64] [64 62 60 59 57 54 51 49] [64 62 60 59 57 54 51 49] 

[12 14 15 18 21 22 23] [23 22 21 18 15 14 12] [23 22 21 18 15 14 12] 

[ 8 10 12 14 17 20] [20 17 14 12 10  8] [ 8 10 12 14 17 20] 

[ 9 10 13 15 18 20 21] [21 20 18 15 13 10  9] [21 20 18 15 13 10  9] 

[26 28 29 32 33 36 39] [39 36 33 32 29 28 26] [26 2

In [56]:
def good_checker(sequence):
    sequence_copy = sequence[1:-1]
    sequence_copy = np.append(sequence_copy, sequence[-1])
    sequence_copy = np.append(sequence_copy, sequence[0])
    diff = sequence - sequence_copy
    diff = np.abs(diff[0:-1])
    if (np.max(diff) < 4) and (np.min(diff) > 0):
        #print(sequence)
        # print(sequence_copy)
        # print(diff)
        ascending = np.sort(sequence)
        descending = np.sort(sequence)[::-1]
        if np.all(ascending == sequence) or np.all(descending == sequence):
            # count += 1
            # print(ascending, descending, sequence, "\n")
            return(True)
        else:   
            return(False)
    else:
        return(False)
        

count = 0
for element in real_data:
    sequence = list(np.array(element.split(' '), dtype=int))
    check = []
    for index in range (0, len(sequence)):
        temp = sequence.copy()
        temp.pop(index)
        check.append(good_checker(np.array(temp)))
    print(sequence, check)
    check = np.array(np.array(check), dtype=int)
    if np.sum(check) >= 1:
        count += 1
        # print(sequence, check)

#wrong 945 432
count


[18, 21, 22, 24, 26, 29, 28] [False, False, False, False, False, True, True]
[9, 11, 14, 17, 18, 21, 21] [False, False, False, False, False, True, True]
[48, 51, 54, 56, 60] [False, False, False, False, True]
[6, 8, 10, 11, 16] [False, False, False, False, True]
[75, 76, 79, 82, 80, 83] [False, False, False, True, True, False]
[28, 31, 33, 32, 33, 30] [False, False, False, False, False, False]
[94, 96, 94, 96, 96] [False, False, False, False, False]
[42, 44, 45, 44, 46, 50] [False, False, False, False, False, False]
[25, 28, 29, 26, 33] [False, False, False, False, False]
[37, 39, 39, 42, 43] [False, True, True, False, False]
[49, 51, 53, 56, 56, 57, 55] [False, False, False, False, False, False, False]
[88, 91, 91, 93, 96, 99, 99] [False, False, False, False, False, False, False]
[56, 59, 59, 61, 62, 65, 68, 72] [False, False, False, False, False, False, False, False]
[30, 33, 35, 37, 39, 42, 42, 49] [False, False, False, False, False, False, False, False]
[14, 17, 19, 23, 24] [False,

465

In [49]:
arr = np.array([True, False, True])
np.array(~arr, dtype=int)

array([0, 1, 0])