In [1]:
import re
import numpy as np

In [2]:
with open('advent2024_4.txt') as file:
    data = file.read().splitlines()

In [3]:
def text_to_matrix(text):
    return [list(row) for row in text]

def matrix_to_text(matrix):
    return [''.join(row) for row in matrix]

def transpose(matrix):
    return np.array(matrix).T.tolist()

def diagonal_matrix(matrix):
    len_y = len(matrix[0]) + len(matrix) - 1
    len_x = len(matrix)
    matrix = np.array([list(row) for row in matrix])
    diagonal_matrix = np.zeros((len_x, len_y), dtype=str)
    for i in range(len_x):
        for j in range(len_y):
            if j >= i and j < i + len(matrix[0]):
                diagonal_matrix[i][j] = matrix[i][j - i]
            else:
                diagonal_matrix[i][j] = '.'

    return diagonal_matrix

def reverse_diagonal_matrix(matrix):
    matrix = np.array([list(row) for row in matrix])
    return diagonal_matrix(matrix[::-1])[::-1]

In [4]:

search = 'XMAS'

def find_elements_original(matrix, search):
    # print('finding original for', matrix)
    text = matrix_to_text(matrix)
    joined_text = ' '.join(text)
    forward_backward = joined_text + ' ' + joined_text[::-1]

    # print('forward_backward', forward_backward)
    elements_fb = re.findall(search, forward_backward)

    updowm_matrix = transpose(matrix)
    updown_text = matrix_to_text(updowm_matrix)
    # print('updown_text', updown_text)

    down_up_matrix = transpose(matrix[::-1])
    downup_text = matrix_to_text(down_up_matrix)
    # print('downup_text', downup_text)

    up_down = ' '.join(updown_text) + ' ' + ' '.join(downup_text)
    elements_ud = re.findall(search, up_down)

    # print('elements_fb', elements_fb)
    # print('elements_ud', elements_ud)

    return elements_fb + elements_ud

def find_elements_updown(matrix, search):
    # print('finding updown for', matrix)

    diagonal_matrix_ = matrix
    # print('diagonal_matrix_ \n', diagonal_matrix_)

    diagonal_updown_matrix = transpose(diagonal_matrix_)
    diagonal_updown_text = matrix_to_text(diagonal_updown_matrix)
    diagonal_updown = ' '.join(diagonal_updown_text)
    # print('diagonal_updown', diagonal_updown)

    diagonal_downup_matrix = transpose(diagonal_matrix_[::-1])
    diagonal_downup_text = matrix_to_text(diagonal_downup_matrix)
    diagonal_downup = ' '.join(diagonal_downup_text)
    # print('diagonal_downup', diagonal_downup)

    total_diagonal = diagonal_updown + ' ' + diagonal_downup
    elements_diag = re.findall(search, total_diagonal)

    # print('elements_diag', elements_diag)

    return elements_diag

def find_elements_diagonal_total(matrix, search):
    diagonal_matrix_ = diagonal_matrix(matrix)
    reverse_diagonal_matrix_ = reverse_diagonal_matrix(matrix)

    return find_elements_updown(diagonal_matrix_, search) + find_elements_updown(reverse_diagonal_matrix_, search)

def find_total_elements(matrix, search):
    return find_elements_original(matrix, search) + find_elements_diagonal_total(matrix, search)



In [5]:
len(find_total_elements(text_to_matrix(data), search))

2562

In [ ]:
#part 2
def find_xmas(matrix):
    # text2_matrix = matrix
    count = 0
    for i, row in enumerate(matrix):
        if i == 0 or i == len(matrix)-1:
            continue
        for j in range(1,len(row)-1):
            
            if row[j] == 'A':
                ul = matrix[i-1][j-1]
                ur = matrix[i-1][j+1]
                bl = matrix[i+1][j-1]
                br = matrix[i+1][j+1]

                #both m at left
                if ul == bl == 'M' and ur == br == 'S':
                    count += 1

                #both m at right
                if ur == br == 'M' and ul == bl == 'S':
                    count += 1

                #both m at top
                if ul == ur == 'M' and bl == br == 'S':
                    count += 1
                
                #both m at bottom
                if bl == br == 'M' and ul == ur == 'S':
                    count += 1

                
    return count

data_matrix = text_to_matrix(data)
find_xmas(data_matrix)

1902

In [ ]:
# def transpose_and_text(text):
#     text = np.array([list(t) for t in text])
#     text = text.T
#     text = [''.join(t) for t in text]
#     return text

# def diagonal_matrix(a):
#     len_y = len(a[0]) + len(a) - 1
#     len_x = len(a)
#     a = np.array([list(row) for row in a])
#     matrix = np.zeros((len_x, len_y), dtype=str)
#     for i in range(len_x):
#         for j in range(len_y):
#             if j >= i and j < i + len(a[0]):
#                 matrix[i][j] = a[i][j - i]
#             else:
#                 matrix[i][j] = '.'

#     text_list = [''.join(row).rstrip() for row in matrix]

#     return text_list


# def reverse_diagonal_matrix(a):
#     a = np.array([list(row) for row in a])
#     return diagonal_matrix(a[::-1])[::-1]

# transpose_and_text(a)

['16a', '27b', '38c', '49d', '50e']

In [61]:
# a = ['12345', '67890', 'abcde']
# b = []
# # matrix from a
# for i in a:
#     b.append(list(i))

# #transpose b and create text
# b = np.array(b).T.tolist()
# text = []
# for i in b:
#     text.append(''.join(i))

# text

In [ ]:


# diagonal_matrix_ = diagonal_matrix(text)
# reverse_diagonal_matrix_ = reverse_diagonal_matrix(text)



# # elements_fb, elements_ud
# # up_dowm_text
# find_elements(diagonal_matrix_, search)

['XMAS', 'XMAS', 'XMAS', 'XMAS', 'XMAS', 'XMAS', 'XMAS']

In [3]:
#change matrix to diagonal
a = ['12345', '67890', 'abcde']




# matrix = np.zeros((len_x, len_y), dtype=str)

# def diagonal_matrix(a):
#     len_y = len(a[0]) + len(a) - 1
#     len_x = len(a)
#     a = np.array([list(row) for row in a])
#     matrix = np.zeros((len_x, len_y), dtype=str)
#     for i in range(len_x):
#         for j in range(len_y):
#             if j >= i and j < i + len(a[0]):
#                 matrix[i][j] = a[i][j - i]
#             else:
#                 matrix[i][j] = '.'

#     text_list = [''.join(row).rstrip() for row in matrix]

#     return text_list
# len_y = len(a[0]) + len(a) - 1
# len_x = len(a)
# a = np.array([list(row) for row in a])
# for i in range(len_x):
#     for j in range(len_y):
#         if j >= i and j < i + len(a[0]):
#             matrix[i][j] = a[i][j - i]
#         else:
#             matrix[i][j] = '.'

# # matrix, a

# # Convert the matrix to a list of strings
# text_list = [''.join(row).rstrip() for row in matrix]

# # Print the list of strings
# print("List of strings:")
# print(text_list)

def reverse_diagonal_matrix(a):
    return diagonal_matrix(a[::-1])[::-1]

new_text = reverse_diagonal_matrix(text) + diagonal_matrix(text)
# find_elements(new_text, search)
new_text

NameError: name 'text' is not defined

In [4]:
text

NameError: name 'text' is not defined

In [5]:
a = ['12345', '67890', 'abcde']
a[::-1]

['abcde', '67890', '12345']

In [6]:
# search = 'XMAS'

# def find_elements(text, search):
#     joined_text = ''.join(text)
#     # forward_backward = joined_text + joined_text[::-1]
#     forward = joined_text
#     backward = joined_text[::-1]

#     up_down = transpose_and_text(text)
#     down_up = up_down[::-1]

#     elements_f = re.findall(search, forward)
#     elements_b = re.findall(search, backward)
#     elements_u = re.findall(search, ''.join(up_down))
#     elements_d = re.findall(search, ''.join(down_up))

#     # up_dowm_text = transpose_and_text(text)
#     # up_down = ''.join(up_dowm_text) + ''.join(up_dowm_text[::-1]) 

#     # elements_fb = re.findall(search, forward_backward)
#     # elements_ud = re.findall(search, up_down)

#     return elements_f + elements_b + elements_u + elements_d

# def find_elements_up_down_only(text, search):
#     up_dowm_text = transpose_and_text(text)
#     up_down = ''.join(up_dowm_text)
#     down_up = ''.join(up_dowm_text[::-1])

#     elements_ud = re.findall(search, up_down)
#     elements_du = re.findall(search, down_up)

#     return elements_ud + elements_du

# def find_elements_diagonal(text, search):
#     diagonal_matrix_ = diagonal_matrix(text)
#     reverse_diagonal_matrix_ = reverse_diagonal_matrix(text)

#     print(diagonal_matrix_)
#     print(reverse_diagonal_matrix_)
#     elements_diag = find_elements_up_down_only(diagonal_matrix_, search)
#     elements_rev_diag = find_elements_up_down_only(reverse_diagonal_matrix_, search)

#     return elements_diag + elements_rev_diag



# # def find_elements_diagonal(text, search):
# #     diagonal_matrix_ = diagonal_matrix(text)
# #     reverse_diagonal_matrix_ = reverse_diagonal_matrix(text)

# #     up_dowm_text_diag = transpose_and_text(diagonal_matrix_)
# #     up_down = ''.join(up_dowm_text_diag) + ''.join(up_dowm_text_diag[::-1]) 

# #     up_dowm_text_rev_diag = transpose_and_text(reverse_diagonal_matrix_)
# #     up_down_rev = ''.join(up_dowm_text_rev_diag) + ''.join(up_dowm_text_rev_diag[::-1])

# #     elements_fb = re.findall(search, up_down)
# #     elements_ud = re.findall(search, up_down_rev)

# #     return elements_ud + elements_fb



# find_elements(text, search), find_elements_diagonal(text, search)

In [7]:
text_, find_elements(text_, search)

NameError: name 'text_' is not defined

In [8]:
diagonal_matrix(text), find_elements_up_down_only(diagonal_matrix(text), search)

NameError: name 'diagonal_matrix' is not defined

In [9]:
reverse_diagonal_matrix(text), find_elements_up_down_only(reverse_diagonal_matrix(text), search)

NameError: name 'text' is not defined

In [10]:
text_= [
    "....XXMAS.",
    ".SAMXMS...",
    "...S..A...",
    "..A.A.MS.X",
    "XMASAMX.MM",
    "X.....XA.A",
    "S.S.S.S.SS",
    ".A.A.A.A.A",
    "..M.M.M.MM",
    ".X.X.XMASX"
]

In [14]:
# find_elements_original(text_to_matrix(text_), search), text_

In [16]:
# transpose(text_to_matrix(text)), diagonal_matrix(text_to_matrix(text_)), reverse_diagonal_matrix(text_to_matrix(text))

In [ ]:
proto_text = ['..X...', 
              '.SAMX.', 
              '.A..A.',
              'XMAS.S',
              '.X....']

In [96]:
a = ['12345', '67890', 'abcde']

a_matrix = text_to_matrix(a)
a, a_matrix, matrix_to_text(a_matrix), transpose(a_matrix), diagonal_matrix(a_matrix)

(['12345', '67890', 'abcde'],
 [['1', '2', '3', '4', '5'],
  ['6', '7', '8', '9', '0'],
  ['a', 'b', 'c', 'd', 'e']],
 ['12345', '67890', 'abcde'],
 [['1', '6', 'a'],
  ['2', '7', 'b'],
  ['3', '8', 'c'],
  ['4', '9', 'd'],
  ['5', '0', 'e']],
 array([['1', '2', '3', '4', '5', '.', '.'],
        ['.', '6', '7', '8', '9', '0', '.'],
        ['.', '.', 'a', 'b', 'c', 'd', 'e']], dtype='<U1'))

In [100]:
text = matrix_to_text(a_matrix)
joined_text = ' '.join(text)
joined_text

'12345 67890 abcde'

In [219]:
text_2 = [
'.M.S......',
'..A..MSMS.',
'.M.S.MAA..',
'..A.ASMSM.',
'.M.S.M....',
'..........',
'S.S.S.S.S.',
'.A.A.A.A..',
'M.M.M.M.M.',
'..........']

In [230]:
text2_matrix = np.array(text_to_matrix(text_2))
text2_matrix.T

array([['.', '.', '.', '.', '.', '.', 'S', '.', 'M', '.'],
       ['M', '.', 'M', '.', 'M', '.', '.', 'A', '.', '.'],
       ['.', 'A', '.', 'A', '.', '.', 'S', '.', 'M', '.'],
       ['S', '.', 'S', '.', 'S', '.', '.', 'A', '.', '.'],
       ['.', '.', '.', 'A', '.', '.', 'S', '.', 'M', '.'],
       ['.', 'M', 'M', 'S', 'M', '.', '.', 'A', '.', '.'],
       ['.', 'S', 'A', 'M', '.', '.', 'S', '.', 'M', '.'],
       ['.', 'M', 'A', 'S', '.', '.', '.', 'A', '.', '.'],
       ['.', 'S', '.', 'M', '.', '.', 'S', '.', 'M', '.'],
       ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.']], dtype='<U1')

In [247]:
data_matrix = np.array(text_to_matrix(data))
np.shape(data_matrix)
data_matrix

array([['S', 'A', 'S', ..., 'A', 'M', 'X'],
       ['A', 'A', 'S', ..., 'A', 'M', 'A'],
       ['M', 'X', 'M', ..., 'A', 'M', 'A'],
       ...,
       ['X', 'X', 'A', ..., 'S', 'X', 'M'],
       ['M', 'M', 'M', ..., 'M', 'M', 'S'],
       ['X', 'M', 'M', ..., 'X', 'S', 'X']], dtype='<U1')

In [227]:
test_matrix = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
test_matrix, test_matrix[::-1], test_matrix.T, test_matrix.T[::-1]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[3, 6, 9],
        [2, 5, 8],
        [1, 4, 7]]))

In [217]:
find_xmas(text2_matrix)

2

In [194]:
range(1, len(text_2[0]))

range(1, 10)